### PR TITLE
fixing broken doc links in README

### PR DESCRIPTION
**Pull request by bshaffer**
adds deployment commands to readme

### CODE REVIEW

**Comment by bshaffer** [comment]
This may be overkill, but then again, it needed to be done.

**Comment by shun-fan** [comment]
LGTM

**Comment by bshaffer** [comment]
@jonparrott want to weigh in on this one?

**Comment by jonparrott** [comment]
Remove the example output, it's noisy. Other than that, LGTM.

**Comment by bshaffer** [comment]
@jonparrott done

**Comment by jonparrott** [comment]
Thanks!

**Pull request merged**
